vim.cmd("hi Folded guibg=none")
vim.cmd("hi FoldColumn guibg=none")

vim.cmd("hi CursorLineNr guifg=#f2f2f2")
vim.cmd("hi CursorLineFold guifg=#f2f2f2")
vim.cmd("hi CursorLine guibg=none")

vim.cmd("hi NeogitBranch guifg=#FFC100")
vim.cmd("hi NeogitSectionHeader guifg=#6c71c4")
vim.cmd("hi NeogitDiffAdd guibg=none guifg=#859900")
vim.cmd("hi NeogitDiffAddHighlight guibg=none guifg=#859900")
vim.cmd("hi NeogitDiffAddCursor guibg=#26292e guifg=#859900")
vim.cmd("hi NeogitDiffDelete guibg=none guifg=#dc322f")
vim.cmd("hi NeogitDiffDeleteHighlight guibg=none guifg=#dc322f")
vim.cmd("hi NeogitDiffDeleteCursor guibg=#26292e guifg=#dc322f")
vim.cmd("hi NeogitDiffContext guibg=none guifg=#839496")
vim.cmd("hi NeogitDiffContextHighlight guibg=none guifg=#839496")
vim.cmd("hi NeogitDiffContextCursor guibg=#26292e guifg=#839496")

vim.cmd("hi FancyDiagnosticHint guifg=#268bd2")
vim.cmd("hi FancyDiagnosticHintIcon guifg=#268bd2")
vim.cmd("hi FancyDiagnosticError guifg=#dc322f")
vim.cmd("hi FancyDiagnosticErrorIcon guifg=#dc322f")
vim.cmd("hi FancyDiagnosticWarn guifg=#b58900")
vim.cmd("hi FancyDiagnosticWarnIcon guifg=#b58900")
