return {
	-- { "onsails/lspkind.nvim" },
	-- { "hrsh7th/cmp-nvim-lsp" },
	-- { "hrsh7th/cmp-buffer" },
	-- { "hrsh7th/cmp-path" },
	-- { "hrsh7th/cmp-cmdline" },
	-- { "hrsh7th/cmp-nvim-lsp-signature-help" },
	-- {
	-- 	"L3MON4D3/LuaSnip",
	-- 	dependencies = { "rafamadriz/friendly-snippets" },
	-- },
	-- { "saadparwaiz1/cmp_luasnip" },
	-- {
	-- 	"hrsh7th/nvim-cmp",
	-- 	config = function()
	-- 		local lspkind = require("lspkind")
	-- 		local cmp = require("cmp")
	-- 		require("luasnip.loaders.from_vscode").lazy_load()
	-- 		cmp.setup({
	-- 			preselect = cmp.PreselectMode.Item,
	-- 			window = {
	-- 				completion = cmp.config.window.bordered({
	-- 					-- border = { "", "", "", "", "", "", "", "▌" },
	-- 					border = { "", "", "", "", "", "", "", "" },
	-- 					winhighlight = "Normal:CmpNormal,CursorLine:CmpSelected,FloatBorder:CmpNormal",
	-- 				}),
	-- 			},
	-- 			snippet = {
	-- 				expand = function(args)
	-- 					require("luasnip").lsp_expand(args.body)
	-- 				end,
	-- 			},
	-- 			mapping = cmp.mapping.preset.insert({
	-- 				["<Tab>"] = cmp.mapping.select_next_item(),
	-- 				["<CR>"] = cmp.mapping.confirm(),
	-- 				["<C-Space>"] = cmp.mapping.complete(),
	-- 			}),
	-- 			sources = cmp.config.sources({
	-- 				{ name = "nvim_lsp" },
	-- 				{ name = "nvim_lsp_signature_help" },
	-- 				{ name = "buffer" },
	-- 				{ name = "path" },
	-- 				{ name = "luasnip" }, -- For vsnip users.
	-- 			}),
	-- 			formatting = {
	-- 				format = lspkind.cmp_format({
	-- 					mode = "text_symbol",
	-- 					maxwidth = 50,
	-- 					ellipsis_char = "...", -- filler char if popup exceeds maxwidth
	-- 				}),
	-- 			},
	-- 			completion = {
	-- 				completeopt = "menu,menuone,noinsert",
	-- 			},
	-- 		})
	-- 	end,
	-- 	enabled = false,
	-- },
}
